from ida_idaapi import BADADDR
from ida_typeinf import tinfo_t, BTF_INT32, BTF_INT64, BTF_CHAR, CM_CC_FASTCALL
from ida_hexrays import mop_visitor_t, optblock_t, m_call, m_mov, mop_r, mop_n, mop_f, minsn_t, mcallarg_t, mcallinfo_t, FCI_SPLOK, FCI_FINAL, FCI_PROP, FCI_NOSIDE

def hash_string(txt):
    h = 0
    btxt = bytes(txt, 'utf-8')

    for i in range(0, len(btxt)):
        h = (btxt[i] + 31 * h) & 0xFFFFFFFF

    return h & 0x7FFFFFFF


known_names = [
    'BlackboardAmy',
    'BlackboardBattle',
    'BlackboardSpeed',
    'BlackboardStatus',
    'BlackboardItem',
    'BlackboardTails',
    'StatePluginAdjustPath',
    'StatePluginAirTrick',
    'StatePluginAmyGadget',
    'StatePluginAquaBall',
    'StatePluginAuraTrain',
    'StatePluginAutoRun',
    'StatePluginBarrierWall',
    'StatePluginBatterBox',
    'StatePluginBattle',
    'StatePluginBoost',
    'StatePluginBoostDrill',
    'StatePluginBoostTarot',
    'StatePluginBossBattle',
    'StatePluginCamera',
    'StatePluginCameraTarget',
    'StatePluginCharmAttack',
    'StatePluginCheckDead',
    'StatePluginCheckExternalInput',
    'StatePluginCollision',
    'StatePluginCyBlasterLift',
    'StatePluginCyBlasterShot',
    'StatePluginCyHammer',
    'StatePluginCyKnuckle',
    'StatePluginCyberStart',
    'StatePluginCyloop',
    'StatePluginCyloopAction',
    'StatePluginCyloopSlash',
    'StatePluginDebug',
    'StatePluginDiving',
    'StatePluginEffect',
    'StatePluginFrame',
    'StatePluginGrind',
    'StatePluginIK',
    'StatePluginInWater',
    'StatePluginInWater',
    'StatePluginInWater',
    'StatePluginInWater',
    'StatePluginLimitedAction',
    'StatePluginManager',
    'StatePluginMasterTrial',
    'StatePluginMaximumHeatKnuckle',
    'StatePluginMinigame',
    'StatePluginOutOfControl',
    'StatePluginPreventLeaveIsland',
    'StatePluginPushBox',
    'StatePluginQuickStep',
    'StatePluginRecovery',
    'StatePluginReflexesPanel',
    'StatePluginRunning',
    'StatePluginSavePermission',
    'StatePluginShot',
    'StatePluginSideview',
    'StatePluginSound',
    'StatePluginSpannerThrow',
    'StatePluginStorm',
    'StatePluginTailsShot',
    'StatePluginTailsSpin',
    'StatePluginTarotRolling',
    'StatePluginThroughOneway',
    'StatePluginWallJump',
    'StatePluginWallMove',
    'ApplicationDisplayOptionExtension',
    'ApplicationFpsExtension',
    'ApplicationInputMapExtension',
    'ApplicationSequenceExtension',
    'GameModeAnimalRescueExtension',
    'GameModeBattleRushExtension',
    'GameModeBossLayerExtension',
    'GameModeBossRushExtension',
    'GameModeCheckPointExtension',
    'GameModeCyberSpaceExtension',
    'GameModeDestinationMarkExtension',
    'GameModeFishingExtension',
    'GameModeGpuInteractionExtension',
    'GameModeHackingExtension',
    'GameModeHsmExtension',
    'GameModeInputExtension',
    'GameModeLayerStatusExtension',
    'GameModeMasterTrialExtension',
    'GameModeNumberRingExtension',
    'GameModeSilverMoonRingExtension',
    'GameModeStageTimeExtension',
    'GameModeTinyFsmExtension',
    'AmbientSoundExtension',
    'BgmIdExtension',
    'CustomSoundExtension',
    'CyberSpaceSoundExtension',
    'HackingSoundExtension',
    'IslandSoundExtension',
    'MovieSoundExtension',
    'PauseMenuSoundExtension',
    'StaffRollSoundExtension',
    'TerrainWorldColorGradingExtension',
    'TerrainWorldDensityExtension',
    'TerrainWorldFogMapExtension',
    'TerrainWorldGismoExtension',
    'TerrainWorldGismoExtension',
    # 'BloomJob',
    # 'CachedShadowMapRenderJob',
    # 'CalcLuminance2Job',
    # 'CallbackJob',
    # 'ChromaticAberrationJob',
    # 'CloudShadowJob',
    # 'ColorAccessibilityFiltereJob',
    # 'ColorContrastJob',
    # 'CombineJob',
    # 'CombineSeparateTranslucencyJob',
    # 'CopyColorJob',
    # 'CopyToBackBufferJob',
    # 'CyberNoiseEffectJob',
    # 'CyberSpaceStartNoiseJob',
    # 'DebugDrawJob',
    # 'DefaultAfterModelRenderJob',
    # 'DefaultAfterResolveDepthJob',
    # 'DefaultDeferredRenderJob',
    # 'DefaultModelRenderJob',
    # 'DefaultPreDeferredPostEffectJob',
    # 'DeferredAmbientRenderJob',
    # 'DeferredDecalJob',
    # 'DeferredRenderJob',
    # 'DeferredShadingJob',
    # 'DepthOfFieldJob',
    # 'DirectionalRadialBlurJob',
    # 'DownSampleJob',
    # 'FieldScanEffectRenderJob',
    # 'FrameBufferCaptureJob',
    # 'FrameBufferCaptureParamBuildJob',
    # 'FXAAJob',
    # 'GodrayJob',
    # 'HeatHazeJob',
    # 'HierarchicalZJob',
    # 'InteractionWaveSimulationJob',
    # 'LitePreDeferredPostEffectJob',
    # 'LocalShadowMapRenderJob',
    # 'LocalShadowModelRenderJob',
    # 'ModelRenderOpPtJob',
    # 'OcclusionCapsuleJob',
    # 'OcclusionCullingViewJob',
    # 'PECallbackJob',
    # 'PEResolveJob',
    # 'PickColorJob',
    # 'PostDeferredPostEffectJob',
    # 'PostEffectLitePipelineJob',
    # 'PostEffectPipelineJob',
    # 'PPECallbackJob',
    # 'PreDeferredPostEffectJob',
    # 'RainOcclusionModelRenderJob',
    # 'RenderableRenderJob',
    # 'RenderDebugScreenJob',
    # 'ResolveDepthJob',
    # 'ResolveJob',
    # 'RLRJob',
    # 'ScreenBlurJob',
    # 'ScreenSpaceGodrayJob',
    # 'SetWorldRTTypeJob',
    # 'ShadowCacheModelRenderJob',
    # 'ShadowHeightMapRenderJob',
    # 'ShadowMapRenderJob',
    # 'ShadowModelRenderJob',
    # 'SkyCubeJob',
    # 'SSAOJob',
    # 'SSGIJob',
    # 'TAAJob',
    # 'TemporalUpscalerJob',
    # 'VignetteJob',

    '_damage',
    '_default',
    '_Default',
    '_homing',
    '_status',
    '?',
    'accel',
    'Accele',
    'AcceleAura',
    'Action',
    'Action_End',
    'ActionChain',
    'ActionChainManager',
    'activate',
    'active',
    'After',
    'AirBoostCyclone',
    'airtrick',
    'alert',
    'always',
    'amy',
    'AmyAdditionalCollider',
    'AmySolid',
    'AmySpin',
    'anim',
    'Anim',
    'anim_logging',
    'AnyModeChangers',
    'appear',
    'ApplyTonemapImmidiate',
    'arcade',
    'ArcLaser',
    'Arm',
    'ArmC',
    'ArmL',
    'Armor',
    'ArmR',
    'AROUND',
    'arrowMat',
    'attack',
    'Attack',
    'ATTACK',
    'attack_end',
    'ATTACK_SHORTDIST',
    'attack_start',
    'attack_stomp',
    'attack01',
    'attack02',
    'attack1',
    'attack2_charge',
    'attack2_end',
    'attack2_start',
    'attack3',
    'attack4',
    'attack5',
    'attack6',
    'Attackable',
    'AttackHitSlow',
    'Attacking',
    'AttackJumpOut',
    'AttackMove',
    'AttackSign',
    'Aura',
    'AutoRun',
    'avoid',
    'back',
    'Ball',
    'BallMove',
    'barrel',
    'Barrier',
    'Base',
    'BatterBox',
    'BattingMachine',
    'battle',
    'Battle2Follow',
    'Battle2FollowNear',
    'BattleMiniBoss',
    'BattleRush',
    'Bee',
    'BeeFlowerAttract',
    'BeeMoveFlower',
    'Before',
    'behind',
    'BGMVolume',
    'BillboardTest',
    'Bind2',
    'Bird',
    'blade_charge_tackle',
    'blade_warp_attack',
    'block',
    'BlockCollider',
    'BlowOff',
    'BLOWOFF',
    'Board',
    'Boarding',
    'body',
    'Body',
    'Body0',
    'Body1',
    'Body2',
    'BodyBack',
    'Bomb',
    'Bonnet',
    'BonusSlot',
    'boomerang',
    'boomerang_start',
    'boost',
    'Boost',
    'BoostAisac',
    'booster',
    'BoostOnCyloop',
    'BoostOnStrider',
    'boot',
    'Boot',
    'Boss',
    'BossAreaEnter',
    'BossAreaLeave',
    'BossDragon',
    'BossFixedCamera',
    'BossGiant',
    'BossGiantQTE',
    'BossKnight',
    'BossOffset',
    'BossPause',
    'BossRifle',
    'BossRifleBeast',
    'bossrush',
    'BossRush',
    'bounce',
    'BoundStomping',
    'brake',
    'BreakedArmor',
    'BREAKING',
    'Breathe',
    'BROKEN',
    'BUILD',
    'BuildLevel',
    'Bullet',
    'BulletTime',
    'BulletTimeBase',
    'Button',
    'cache',
    'Cage',
    'camera',
    'cannon_barrel',
    'cannon_base',
    'cannon_rot',
    'cannonMat',
    'CarryAnimal',
    'Catch',
    'Challenge',
    'CHANGE',
    'change_Black',
    'change_White',
    'ChangeQTE',
    'ChaosEmerald',
    'ChaosEmeraldStorage',
    'CharactorControl',
    'charge',
    'CHARGE',
    'ChargeAttack',
    'ChargeAttackLast',
    'charmattack',
    'charmlock',
    'CHASE',
    'ChaseSensor',
    'chr_supersonic2',
    'Claw',
    'Claw2_1',
    'Claw2_2',
    'clear',
    'Clear',
    'ClearedStage',
    'ColDeformationInvalid',
    'CollisionQuery',
    'combo',
    'ContactDamage',
    'ContactSphere',
    'ContinueSkill',
    'controller',
    'Controller',
    'copy',
    'CopyCyloop',
    'Core',
    'Counter',
    'Counter2',
    'Crane',
    'Credit',
    'CrossLine',
    'CursorDecideAnimation',
    'CustomGraphicEnabled',
    'cyArmorIdleA',
    'cyArmorIdleB',
    'cyArmorIdleC',
    'cyber',
    'CyberModeNitro',
    'CyberStage',
    'CyberStageChallenge',
    'CyBlaster',
    'CyBlasterHit',
    'CyBlasterLift',
    'CyBlasterLiftFall',
    'CyBlasterLiftJump',
    'CyBlasterLiftRun',
    'Cyclone',
    'CycloneBoost',
    'cylinder',
    'cyloop',
    'Cyloop',
    'cyloopBlinkA',
    'cyloopBlinkB',
    'cyloopBlinkC',
    'cyloopDamageA',
    'cyloopDamageB',
    'cyloopDamageC',
    'cyloopIdleA',
    'cyloopIdleB',
    'cyloopIdleC',
    'cyloopVanishA',
    'cyloopVanishB',
    'cyloopVanishC',
    'damage',
    'Damage',
    'DAMAGE',
    'Damage_Atackle',
    'Damage_Player',
    'damageBL',
    'damageBLUpdate',
    'damageBR',
    'damageBRUpdate',
    'DamageCol',
    'damageCommon',
    'Damaged',
    'damaged_body',
    'DamageEffect',
    'damageFL',
    'damageFLUpdate',
    'damageFR',
    'damageFRUpdate',
    'DamageHitStop',
    'DamageInvincible',
    'DamageRunning',
    'Dark',
    'Dash',
    'DashRing',
    'dead',
    'Dead',
    'Debris',
    'deformIn',
    'deformOut',
    'detect_puck',
    'disable',
    'DisableChangeMode',
    'DisabledCSMCache',
    'disappear',
    'DistanceToTarget',
    'Diving',
    'DivingFall',
    'DivingSlipStream',
    'DivingSlipStreamFast',
    'DOF',
    'DOFBase',
    'door',
    'down',
    'Dragon_Battle',
    'Dragon_Climb',
    'dragon_damage',
    'Dragon_FC',
    'DragonIncident',
    'Drill',
    'drop_ring',
    'Drum',
    'Dummy',
    'DummyJump',
    'duplicate',
    'duplicatesp',
    'DvStandardCharacter',
    'dynamics',
    'EDIT',
    'Eff_Muzzle_R',
    'Egg',
    'EggTrans',
    'electric',
    'end',
    'end_ik',
    'enemy_hightspeed_trial',
    'EnemyTutorial',
    'EnergyLine',
    'ev_boss_cylinder01_OBJ',
    'Event',
    'EventCapture',
    'EventEnvironmentPlayer',
    'EventEnvironmentSave',
    'EventEnvironmentTime',
    'EventPreviewCapture',
    'EventPreviewHelperWindow',
    'Expansion',
    'explo',
    'explosion',
    'ExplosionKodamaCollection01',
    'ExplosionKodamaCollection02',
    'Eyesight',
    'Facial',
    'FailSafe',
    'Fall',
    'FallingDead',
    'FallWithAnimal',
    'FallWithCannonball',
    'FallWithKodama',
    'Fan',
    'Fang',
    'Fang2',
    'FastTravel',
    'FastTravelPause',
    'FILL',
    'FindTarget',
    'fire',
    'FirstFollowCamera',
    'Fishing',
    'FishingPortal',
    'FixedAction',
    'FixedActionReset',
    'fixedTime',
    'Flame',
    'fly_b_boost_loop',
    'fly_f_loop',
    'fly_start',
    'follow',
    'FollowCamera',
    'ForetasteSign',
    'FS_angleMax',
    'FS_distance',
    'FS_height',
    'FS_radius',
    'FxParamChromaticAberrationExtension',
    'FxParamEdit',
    'GameConfigFirstUID',
    'GameConfigIndex',
    'GameModeBattleRush',
    'GameModeBossLayerExtension',
    'GameModeBossRush',
    'GameModeMasterTrial',
    'GameModeStage',
    'GameModeStageMainMenu',
    'Gauge',
    'Gaze',
    'Giant_Battle',
    'Giant_Climb',
    'GiantDashCircle',
    'GiantIncident',
    'gimmick',
    'glide',
    'Gliding',
    'Goal',
    'gocCyblasterTrigger',
    'Grab',
    'GraphicFirstUID',
    'GraphicIndex',
    'GraphicsOption',
    'grind',
    'grind_cap_head',
    'grind_cap_tail',
    'GrindDamage',
    'GrindDamageAir',
    'gs',
    'GUARD',
    'GuardLeg',
    'HA',
    'hacking',
    'Hacking',
    'hacking_exit',
    'Hall',
    'Hammer',
    'Hangglider',
    'HardStun',
    'Head',
    'HeadFront',
    'HealthRatio',
    'High',
    'HIT_COL',
    'HitLand',
    'HitMesh',
    'HitPlayer',
    'HITPLAYER',
    'hold',
    'HoldStand',
    'Hologram',
    'homing',
    'HomingFinish',
    'HomingLaser',
    'hop',
    'Howl',
    'hp1',
    'hp2',
    'hp3',
    'Human',
    'HumanTrans',
    'idle',
    'Idle',
    'IDLE',
    'idle_Black',
    'idle_near_loop',
    'idle_near_start',
    'idle_White',
    'idleUpdate',
    'ik',
    'IK_Adjustment',
    'Impulse',
    'InAttackRange',
    'initial',
    'Initial_Damage_Emd',
    'Inner',
    'InnerShell',
    'insertmovie',
    'InTerritory',
    'interrupt',
    'Interrupt',
    'InterruptCamera',
    'InTutorial',
    'invincible',
    'InWater',
    'IsAttacker',
    'island',
    'island_extra',
    'IslandSpring',
    'IslandStage',
    'JumpBoardLaunch',
    'JumpWithAnimal',
    'JumpWithKodama',
    'justparry',
    'KeyConfigFirstUID',
    'KeyConfigIndex',
    'Kill',
    'kinematics',
    'Knight_Battle',
    'Knight_Climb',
    'KnightClimbIdleStart',
    'KnightFC',
    'KnightIncident',
    'KnockBack',
    'Knockback_End',
    'Knockback_Rot_Normal',
    'knuckles',
    'KnucklesAdditionalCollider',
    'KnucklesSpin',
    'Kodama',
    'KodamaElder',
    'KodamaHermit',
    'KodamaMap',
    'KodamaMasterFixedCamera',
    'KodamaMasterKing',
    'KodamaPeddler',
    'land',
    'Large',
    'laser',
    'Laser',
    'LASER_COL',
    'laser_quick_loop',
    'LaserTarget',
    'LaserVisual',
    'LastHit',
    'Launch',
    'LavaDead',
    'Level1TabIndex',
    'Level2TabIndex',
    'Levitation',
    'light',
    'Light',
    'LIGHT',
    'limitHeight',
    'loadgame',
    'LoadSaveDataList',
    'LoadSlotExtra',
    'LoadSlotNo',
    'lock',
    'LookAt',
    'loop',
    'LoopKick',
    'Low',
    'Main',
    'MapScan',
    'MarkedCheckPoint',
    'MasterTrial',
    'MasterVolume',
    'mat',
    'matbody',
    'MaximumHeatKnuckle',
    'MaximumHeatKnuckleLast',
    'MaxSpeedChallenge',
    'menu',
    'menuload_changestage',
    'MenuQuit',
    'Mesh',
    'message',
    'MeteorShowerService',
    'minigame',
    'Minigame',
    'mintime',
    'MissileCollider',
    'MissileGeometry',
    'Mode',
    'ModeChanging',
    'Model',
    'ModelRoot',
    'ModeTime',
    'monologue',
    'monologue-time',
    'motion',
    'MotionCamera',
    'MotionCamera0',
    'Move',
    'MOVE',
    'Move_Foot',
    'Movement',
    'moviepause',
    'MOVING',
    'MsgBeginOutOfControl',
    'MusicSelect',
    'MusicSelectType',
    'NearCamera',
    'NEEDLE',
    'newgame',
    'next',
    'NextMode',
    'nitro',
    'Nitro',
    'NitroBase',
    'noaction',
    'NodeFocusCamera',
    'NoiseBias',
    'NoiseBiasZero',
    'NoisePreset',
    'None',
    'NotLandingTime',
    'NotSelectLayer',
    'NotStand',
    'NPC',
    'null',
    'ObjChaosEmerald',
    'ObjGiantCannon',
    'ObjGiantCannon:LoadingTrigger',
    'ObjOneWayPanelManager',
    'ObjTimeBomb',
    'ObjTimeBomb:Put',
    'off',
    'omen',
    'on',
    'On',
    'OnGround',
    'OnGroundImpulse',
    'OnRobberSensor',
    'Option',
    'OriginalCyloop',
    'Outer',
    'OuterShell',
    'OutOfControl',
    'overheat',
    'overheat2',
    'OverlayWindowOpen',
    'OverrideAsm',
    'pack_All_respawn',
    'pack_L_respawn',
    'pack_R_respawn',
    'Paralysis',
    'ParamChanged',
    'Parried',
    'parry',
    'Parry',
    'Parry_End',
    'parry_tails',
    'ParryEnable',
    'ParryKnockBack',
    'Path',
    'pause',
    'Phase1Bind1',
    'Phase2Bind1',
    'PhotoMode',
    'PhotoModeActiveDeviceManagerAddListener',
    'PhotoModeCreateCurrentScreenImage',
    'piece',
    'Piece',
    'Pillar',
    'Pinball',
    'PipeIn',
    'PipeMove',
    'Platform',
    'play',
    'PLAY_COL',
    'play_eff_charge',
    'Player',
    'PlayerAttacking',
    'PlayerDamage',
    'PlayerHide',
    'PlayerHold',
    'PlayerOffset',
    'PointCamera0',
    'Portal',
    'practice',
    'press',
    'press_end',
    'PressDead',
    'preWait',
    'propeller',
    'Propeller',
    'Property',
    'PullCamera',
    'Punch1',
    'Punch2',
    'QteCameraChange',
    'Query',
    'Quest',
    'QuestManager',
    'Quick_End',
    'railDisappear',
    'RailEnd',
    'Raycast',
    'reaction',
    'ReadyTime',
    'rebirth',
    'RebuildLevel',
    'RecoveryRingModeDisable',
    'red',
    'reentryTime',
    'ReflectionStatus',
    'ReleaseSkill',
    'remove',
    'ResetCamera',
    'result',
    'Retry',
    'retry_changestage',
    'RetryFromMenu',
    'RetryFromMiss',
    'RetryFromResult',
    'ReturnCol',
    'Rifle',
    'Rifle_Battle',
    'RifleBeast',
    'RightA',
    'Rigid',
    'RIGID',
    'RigidBody',
    'RigidBody0',
    'RigidBody1',
    'ring',
    'Ring',
    'RingGate',
    'ringUV',
    'Rock',
    'Roof',
    'Rot',
    'Rot_Start',
    'rotate',
    'RunningStart',
    'RunWithAnimal',
    'RunWithCannonball',
    'RunWithKodama',
    'S',
    'SandSki',
    'SandSkiBlow',
    'SandSkiPylonHit',
    'SandStorm',
    'SaveEnabled',
    'SaveGiantCrane',
    'SaveLoaded',
    'SaveMenuTab',
    'SaveMode',
    'SaveSlotNo',
    'SaveStaffRole',
    'SaveTombStone',
    'Script',
    'ScriptSave',
    'ScriptSequence',
    'Search',
    'SearchSphere',
    'SecondFollowCamera',
    'SelectSystemItemIndex',
    'Sensor',
    'SENSOR',
    'sensor_arm',
    'SensorGimmick',
    'SequenceSwitchVolumeMainMenu',
    'SequenceSwitchVolumeMapMenu',
    'SEVolume',
    'ShadowCameraTest',
    'ShadowLightDirection',
    'ShakeCamera',
    'shot',
    'Shot',
    'shot_loop',
    'ShotLaser',
    'shutdown',
    'SideView',
    'sign',
    'Slash',
    'sleep',
    'slingshot_charge01',
    'slingshot_charge02',
    'smash',
    'Smash1',
    'Smash2',
    'sniper_stun',
    'sonic',
    'Sonic',
    'SonicSpin',
    'SoundIndex',
    'Spanner',
    'SpCounter03',
    'Speed_Change',
    'Sphere',
    'SpiderArmorBreak',
    'SpiderBlownDown',
    'SpiderBlownUp',
    'SpiderFall',
    'SpiderFootUp',
    'Spin0',
    'Spin1',
    'SpinAttack',
    'SpinBoostOverHeat',
    'SpinSlash',
    'SpinSlashBall',
    'SpinSlashLast',
    'spring',
    'Spring',
    'SpringJump',
    'Stand',
    'standby',
    'StandWithAnimal',
    'StandWithCannonball',
    'StandWithKodama',
    'start',
    'Start',
    'StartPhotoMode',
    'StatePluginPreventLeaveIsland',
    'Statue',
    'Step_End',
    'Step_Move',
    'StepMove',
    'stomp',
    'StompingAttack',
    'StompingAttackLast',
    'stop',
    'StopMotionCamera',
    'StoppedStage',
    'Storage',
    'StorageKey',
    'Storm',
    'StraightJump',
    'strongnewgame',
    'stun_start',
    'stunse',
    'SuffocatingDead',
    'SunParamExtensionChangeParam',
    'SuperSonic',
    'SuperSonic2',
    'SuperSonicSpin',
    'SureHit',
    'Tail',
    'tails',
    'TailsFly',
    'TailsSpin',
    'TargetInTerritory',
    'Tarot',
    'TarotAttack',
    'TarotBuild',
    'TarotRolling',
    'Test',
    'TextBoxListChanged',
    'TheEnd',
    'Thorn',
    'time',
    'TimeBall',
    'TimeBomb',
    'timeout',
    'Timeout',
    'timerBase',
    'timeup',
    'TimeUpDead',
    'title',
    'ToClose',
    'TombStone',
    'Top',
    'TOP',
    'touched',
    'TouchedWater',
    'Tower',
    'TraceStone',
    'TrackerCamera',
    'TrackerCamera2',
    'TrackerPractice',
    'Trail',
    'TrailFloor',
    'TransitFall',
    'TransitStage',
    'Trigger',
    'turn_l',
    'turn_one_step',
    'turn_r',
    'turnback',
    'TurnMove',
    'turret',
    'Tutorial',
    'tutorial_by_dead',
    'tutorial_by_notify',
    'tutorial_by_skill',
    'TutorialBGM',
    'typhoon',
    'UmbrellaJump',
    'unlock',
    'UpdateGameConfig',
    'UpdateGameConfigVolume',
    'UpdateGraphic',
    'UpdateGraphicVolume',
    'UpdateKeyConfig',
    'UpdateKeyConfigVolume',
    'UpdateLevel1Tab',
    'UpdateLevel2Tab',
    'UpdateOpitionForHud',
    'UpdateSave',
    'UpdateSaveDataList',
    'UpdateSound',
    'UpdateSoundVolume',
    'UpdateSystem',
    'UpDead',
    'Uppercut',
    'Use_Atackle',
    'uv',
    'uvbody',
    'vanish',
    'VANISH',
    'visual',
    'Visual',
    'voice',
    'VoiceVolume',
    'w0r21_ms1_wallrock_D',
    'w0r21_ms1_wallrock_M',
    'w0r21_sk1_island_001',
    'w0r21_sk1_island_002',
    'w0r21_sk1_island_A',
    'w0r21_sk1_island_B',
    'w0r21_sk1_island_F',
    'w0r21_sk1_island_G',
    'w0r21_sk1_wallA_003',
    'w0r21_tk1_cliff',
    'w0r21_tk1_cliff_high',
    'wait',
    'walkse',
    'Wall',
    'WallSolid',
    'WallTrigger',
    'warship',
    'WarshipCamera',
    'WeakPoint',
    'weather_inwater',
    'WindowOpen',
    'ZoomCamera',
]

known_names_map = { hash_string(nam): nam for nam in known_names }

# def generate_name_load(ea, reg, name):
#     print(f'EA: {ea}')
#     insn = minsn_t(ea)
#     insn.opcode = m_mov
#     insn.l._make_strlit(name)
#     insn.l.size = 8
#     insn.r.zero()
#     insn.d.make_reg(reg)
#     insn.d.size = 8

#     return insn

def generate_hashed_string_call(ea, name, siz):
    cchar = tinfo_t()
    cchar.create_simple_type(BTF_CHAR)
    cchar.set_const()

    nameargtype = tinfo_t()
    nameargtype.create_ptr(cchar)

    namearg = mcallarg_t()
    namearg._make_strlit(name)
    namearg.type = nameargtype
    namearg.size = nameargtype.get_size()
    namearg.name = "name"

    returntype = tinfo_t()
    returntype.create_simple_type(BTF_INT64 if siz == 8 else BTF_INT32)

    callinfo = mcallinfo_t(BADADDR, 1)
    callinfo.flags = FCI_SPLOK | FCI_FINAL | FCI_PROP | FCI_NOSIDE
    callinfo.cc = CM_CC_FASTCALL
    callinfo.args.push_back(namearg)
    callinfo.return_type = returntype

    callinsn = minsn_t(ea)
    callinsn.opcode = m_call
    callinsn.l.make_helper("csl::ut::HashedString")
    callinsn.r.zero()
    callinsn.d.t = mop_f
    callinsn.d.f = callinfo
    callinsn.d.size = siz

    # movinsn = minsn_t(ea)
    # movinsn.opcode = m_mov
    # movinsn.l.create_from_insn(callinsn)
    # movinsn.r.zero()
    # movinsn.d.t = mop_r
    # movinsn.d.r = 0
    # movinsn.d.size = 8

    return callinsn


class subinsn_optimizer_t(mop_visitor_t):
    new_insns = []
    cnt = 0

    def __init__(self, curblock):
        super().__init__()
        self.curblock = curblock

    def visit_mop(self, op, t, is_target):
        # print(f'trying {op.dstr()}')
        if is_target:
            return 0
        
        if op.t != mop_n:
            return 0
        
        h = op.nnn.value
        
        if h not in known_names_map:
            return 0
        
        name = known_names_map[h]

        # reg = self.mba.alloc_kreg(8)
        # nameinsn = generate_name_load(self.curins.ea, reg, name)

        # print(f'name insn: {nameinsn.dstr()}')

        # previns = self.topins.prev
        # self.blk.insert_into_block(nameinsn, previns)

        siz = op.size
        callinsn = generate_hashed_string_call(self.curins.ea, name, siz)

        op.erase()
        op.create_from_insn(callinsn)
        op.size = siz
        self.cnt += 1

        print(f'after: {self.curins.dstr()}')

        return 0


class NameHashOptimizer(optblock_t):
    def func(self, blk):
        opt = subinsn_optimizer_t(blk)
        blk.for_all_ops(opt)
        if opt.cnt != 0:
            blk.mark_lists_dirty()
            blk.mba.verify(True)
        return opt.cnt

try:
    namehash_optimizer
    try:
        namehash_optimizer.remove()
        del namehash_optimizer
        print('namehash_optimizer unregistered')
    except Exception as err:
        print(str(err))
except:
    namehash_optimizer = NameHashOptimizer()
    namehash_optimizer.install()
    print('namehash_optimizer installed')
