from ida_nalt import retrieve_input_file_sha256
from ida_funcs import get_fchunk
from ida_ua import o_phrase, o_displ, o_reg
from rangers_analysis.lib.ua_data_extraction import find_insn_forward, track_values, decoded_insns_forward
from rangers_analysis.lib.iterators import find

rangers_analysis_config = None

def looks_like_instantiator_wars(f):
    return find_insn_forward(lambda d: d.mnem == 'call' and d.insn.Op1.addr in rangers_analysis_config['allocator_addresses'], f.start_ea, f.end_ea)

def looks_like_instantiator_rangers(f):
    # Our little tracing asm walker can't deal with multi-chunk functions, so just take the first chunk so it doesn't crash
    f = get_fchunk(f.start_ea)

    # Check if we try to read out the vtable of rcx, presumably the allocator.
    vtbl_res = find(
        lambda i: i[0].mnem == 'mov' and i[0].insn.Op1.type == o_reg and i[0].insn.Op2.type == o_phrase and i[0].insn.Op2.reg in i[1]['allocator'].regs,
        track_values({ 'allocator': 1 }, decoded_insns_forward(f.start_ea, f.end_ea))
    )
    if not vtbl_res: return False
    vtbl_insn, at_vtbl_insn_values = vtbl_res
    after_vtbl_insn_values = { **at_vtbl_insn_values, 'alloc_vtable': vtbl_insn.insn.Op1.reg }

    # See if we do a direct call on a displacement operand
    displ_call_res = find(
        lambda i: i[0].mnem == 'call' and i[0].insn.Op1.type == o_displ and i[0].insn.Op1.addr == 8 and i[0].insn.Op1.reg in i[1]['alloc_vtable'].regs and 1 in i[1]['allocator'].regs,
        track_values(after_vtbl_insn_values, decoded_insns_forward(vtbl_insn.ea + vtbl_insn.size, f.end_ea))
    )
    if displ_call_res: return True

    # Otherwise, see if we first read out the function pointer separately and then do a call on a register
    allocfn_res = find(
        lambda i: i[0].mnem == 'mov' and i[0].insn.Op1.type == o_reg and i[0].insn.Op2.type == o_displ and i[0].insn.Op2.addr == 8 and i[0].insn.Op2.reg in i[1]['alloc_vtable'].regs,
        track_values(after_vtbl_insn_values, decoded_insns_forward(vtbl_insn.ea + vtbl_insn.size, f.end_ea))
    )
    if not allocfn_res: return False
    allocfn_insn, at_allocfn_insn_values = allocfn_res
    after_allocfn_insn_values = { **at_allocfn_insn_values, 'allocfn': allocfn_insn.insn.Op1.reg }

    call_res = find(
        lambda i: i[0].mnem == 'call' and i[0].insn.Op1.type == o_reg and i[0].insn.Op1.reg in i[1]['allocfn'].regs and 1 in i[1]['allocator'].regs,
        track_values(after_allocfn_insn_values, decoded_insns_forward(allocfn_insn.ea + allocfn_insn.size, f.end_ea))
    )
    if call_res: return True

    return False

available_configs = {
    'rangers': {
        '1.41': {
            'steam': {
                'sdk_env_var': 'SONIC_FRONTIERS_SDK',
                'sdk_prefix': 'RangersSDK',
                'segments': {
                    'data': '.trace',
                    'rdata': '.udata',
                    'text': '.data',
                    'denuvoized_text': '.sxdata',
                },
                'pass_allocator': True,
                'namespaces': {
                    'rfl': {
                        'FxBloomParameter': ['needle', 'hh'],
                        'FxDOFParameter': ['needle', 'hh'],
                        'FxColorContrastParameter': ['needle', 'hh'],
                        'FxToneMapParameter': ['needle', 'hh'],
                        'FxCameraControlParameter': ['needle', 'hh'],
                        'FxShadowMapParameter': ['needle', 'hh'],
                        'FxShadowHeightMapParameter': ['needle', 'hh'],
                        'FxVolumetricShadowParameter': ['needle', 'hh'],
                        'FxScreenBlurParameter': ['needle', 'hh'],
                        'FxSSAOParameter': ['needle', 'hh'],
                        'FxSHLightFieldParameter': ['needle', 'hh'],
                        'FxLightScatteringParameter': ['needle', 'hh'],
                        'FxRLRParameter': ['needle', 'hh'],
                        'FxSSGIParameter': ['needle', 'hh'],
                        'FxPlanarReflectionParameter': ['needle', 'hh'],
                        'FxOcclusionCapsuleParameter': ['needle', 'hh'],
                        'FxGodrayParameter': ['needle', 'hh'],
                        'FxScreenSpaceGodrayParameter': ['needle', 'hh'],
                        'FxHeatHazeParameter': ['needle', 'hh'],
                        'FxSceneEnvironmentParameter': ['needle', 'hh'],
                        'FxRenderOption': ['needle', 'hh'],
                        'FxSGGIParameter': ['needle', 'hh'],
                        'FxTAAParameter': ['needle', 'hh'],
                        'FxEffectParameter': ['needle', 'hh'],
                        'FxAtmosphereParameter': ['needle', 'hh'],
                        'FxDensityParameter': ['needle', 'hh'],
                        'FxWindComputeParameter': ['needle', 'hh'],
                        'FxGpuEnvironmentParameter': ['needle', 'hh'],
                        'FxInteractiveWaveParameter': ['needle', 'hh'],
                        'FxChromaticAberrationParameter': ['needle', 'hh'],
                        'FxVignetteParameter': ['needle', 'hh'],
                        'FxTerrainMaterialBlendingParameter': ['needle', 'hh'],
                        'FxWeatherParameter': ['needle', 'hh'],
                        'FxColorAccessibilityFilterParameter': ['needle', 'hh'],
                        'FxCyberNoiseEffectParameter': ['needle', 'hh'],
                        'FxCyberSpaceStartNoiseParameter': ['needle', 'hh'],
                        'FxCyberNPCSSEffectRenderParameter': ['needle', 'hh'],
                        'FxDentParameter': ['gfx', 'hh'],
                        'FxFieldScanEffectRenderParameter': ['needle', 'hh'],
                        'FxSeparableSSSParameter': ['needle', 'hh'],
                        'FxRenderTargetSetting': ['gfx', 'hh'],
                        'FxAntiAliasing': ['needle', 'hh'],
                        'StageCommonAtmosphereParameter': ['gfx', 'hh'],
                        'FxLODParameter': ['needle', 'hh'],
                        'FxDetailParameter': ['needle', 'hh'],
                        'FxDynamicResolutionParameter': ['needle', 'hh'],
                        'FxPlanarProjectionShadowParameter': ['needle', 'hh'],
                        'FxSunPosAngle': ['needle', 'hh'],
                        'FxSunPosEarth': ['needle', 'hh'],
                        'FxSun': ['needle', 'hh'],
                        'FxMoon': ['needle', 'hh'],
                        'FxSkyCommon': ['needle', 'hh'],
                        'FxManualHeightFog': ['needle', 'hh'],
                        'FxHeightFog': ['needle', 'hh'],
                        'FxSebastienSky': ['needle', 'hh'],
                        'FxBrunetonSky': ['needle', 'hh'],
                        'FxBrunetonSkyNight': ['needle', 'hh'],
                        'FxDensityWindParameter': ['needle', 'hh'],
                        'FxTerrainParameter': ['needle', 'hh'],
                        'FxDropParameter': ['needle', 'hh'],
                        'FxPuddleParameter': ['needle', 'hh'],
                        'FxRippleParameter': ['needle', 'hh'],
                        'FxRainParameter': ['needle', 'hh'],
                        'FxDistanceFogParameter': ['needle', 'hh'],
                        'FxHeightFogParameter': ['needle', 'hh'],
                        'FxFogParameter': ['needle', 'hh'],
                        'FxInteractionDebugParameter': ['needle', 'hh'],
                        'FxInteractionParameter': ['needle', 'hh'],
                        'FxModelParameter': ['needle', 'hh'],
                        'FxAutoExposureParameter': ['needle', 'hh'],
                        'FxDirectionalRadialBlurParameter': ['needle', 'hh'],
                        'FxFXAAParameter': ['needle', 'hh'],
                        'FxGodrayVolumeTexture': ['needle', 'hh'],
                        'FxHBAO_Parameter': ['needle', 'hh'],
                        'FxHeightMapParameter': ['needle', 'hh'],
                        'FxLightFieldMergeParameter': ['needle', 'hh'],
                        'FxManualExposureParameter': ['needle', 'hh'],
                        'FxPlanarProjectionShadowParameter': ['needle', 'hh'],
                        'FxSMAAParameter': ['needle', 'hh'],
                        'FxSSAO_Parameter': ['needle', 'hh'],
                        'FxSSS_Parameter': ['needle', 'hh'],
                        'FxSSGIDebugParameter': ['needle', 'hh'],
                        'FxToneMapParameterFilmic': ['needle', 'hh'],
                        'FxToneMapParameterGT': ['needle', 'hh'],
                        'FxVfDepthParameter': ['needle', 'hh'],
                        'FxVfImageCircleParameter': ['needle', 'hh'],
                        'FxVfLineParameter': ['needle', 'hh'],
                        'FxWindComputeDebugParameter': ['needle', 'hh'],
                        'FxCloudBlendParameter': ['needle', 'hh'],
                        'FxCloudProcedural': ['needle', 'hh'],
                        'FxCloudShadowParameter': ['needle', 'hh'],
                        'FxCrepuscularRay': ['needle', 'hh'],
                        'FxDensityParameter': ['needle', 'hh'],
                        'FxDensityLodParameter': ['needle', 'hh'],
                        'FxDensityDebugParameter': ['needle', 'hh'],
                        'ColorDropout': ['needle', 'hh'],
                        'ColorShift': ['needle', 'hh'],
                        'DebugScreenOption': ['needle', 'hh'],
                        'FxAntiAliasing': ['needle', 'hh'],
                        'FxBloomParameter': ['needle', 'hh'],
                        'FxCameraControlParameter': ['needle', 'hh'],
                        'FxChromaticAberrationParameter': ['needle', 'hh'],
                        'FxColorAccessibilityFilterParameter': ['needle', 'hh'],
                        'FxColorContrastParameter': ['needle', 'hh'],
                        'FxCyberSpaceStartNoiseParameter': ['needle', 'hh'],
                        'StageCommonTimeProgressParameter': ['gfx', 'hh'],
                        'NeedleFxSceneConfig': ['needle', 'hh'],
                        'NeedleFxParameter': ['needle', 'hh'],
                        'NeedleFxSceneData': ['needle', 'hh'],
                        'PlayLog': ['save', 'app'],
                        'PlayStatsSummary': ['save', 'app'],
                        'PlayStatsData': ['save', 'app'],
                        'PlayStats': ['save', 'app'],
                        'ScoreAndRnakData': ['save', 'app'],
                        'ActionChainStruct': ['save', 'app'],
                        'HeaderData': ['save', 'app'],
                        'CyberStageData': ['save', 'app'],
                        'CyberStageContainerData': ['save', 'app'],
                        'ArcadeData': ['save', 'app'],
                        'ChallengeBattleRushScoreData': ['save', 'app'],
                        'ChallengeBattleRushData': ['save', 'app'],
                        'ChallengeBattleRushContainerData': ['save', 'app'],
                        'ChallengeCyberStageData': ['save', 'app'],
                        'ChallengeCyberStageContainerData': ['save', 'app'],
                        'ChallengeData': ['save', 'app'],
                        'CharacterData': ['save', 'app'],
                        'ExtraCharacterData': ['save', 'app'],
                        'ExtraCharacterContainerData': ['save', 'app'],
                        'ExtraCyberStageContainerData': ['save', 'app'],
                        'WorldFlagData': ['save', 'app'],
                        'ExtraFlagData': ['save', 'app'],
                        'ExtraFlagContainerData': ['save', 'app'],
                        'IslandMapGridData': ['save', 'app'],
                        'IslandMapData': ['save', 'app'],
                        'IslandStageData': ['save', 'app'],
                        'ExtraIslandStageContainerData': ['save', 'app'],
                        'FlagContainerData': ['save', 'app'],
                        'GamePlayData': ['save', 'app'],
                        'IslandStageContainerData': ['save', 'app'],
                        'WorldFlagContainerData': ['save', 'app'],
                        'ReservedData': ['save', 'app'],
                        'StatValue': ['save', 'app'],
                        'StatsContainerData': ['save', 'app'],
                        'WeatherTimerData': ['save', 'app'],
                        'WeatherBlockData': ['save', 'app'],
                        'WeatherData': ['save', 'app'],
                        'GameData': ['save', 'app'],
                        'PlayLogCoordData': ['save', 'app'],
                        'PlayLogEventData': ['save', 'app'],
                        'PlayLogData': ['save', 'app'],
                        'GameDataInPlayLog': ['save', 'app'],
                        'OptionAudioData': ['save', 'app'],
                        'OptionCameraData': ['save', 'app'],
                        'OptionControlsData': ['save', 'app'],
                        'OptionGamePlayData': ['save', 'app'],
                        'OptionGraphicsData': ['save', 'app'],
                        'OptionData': ['save', 'app'],
                    },
                    'resources': {
                        'ResAtomConfig': ['snd', 'hh'],
                        'ResAtomCueSheet': ['snd', 'hh'],
                        'ResMirageLight': ['gfx', 'hh'],
                        'ResMaterial': ['gfx', 'hh'],
                        'ResTerrainModel': ['gfx', 'hh'],
                        'ResModel': ['gfx', 'hh'],
                        'ResComputeShader': ['gfnd', 'hh'],
                        'ResFragmentShader': ['gfnd', 'hh'],
                        'ResVertexShader': ['gfnd', 'hh'],
                        'ResTexture': ['gfnd', 'hh'],
                        'ResLevel': ['level', 'app'],
                        'ResMasterLevel': ['level', 'app'],
                        'ResBitmapFont': ['font', 'hh'],
                        'ResScalableFontSet': ['font', 'hh'],
                        'ResReflection': ['fnd', 'hh'],
                        'Packfile': ['fnd', 'hh'],
                        'ResEffect': ['eff', 'hh'],
                    },
                },
                'heuristics': {
                    'looks_like_instantiator': looks_like_instantiator_rangers,
                },
                'rfl_member_types': [
                    'TYPE_VOID',
                    'TYPE_BOOL',
                    'TYPE_SINT8',
                    'TYPE_UINT8',
                    'TYPE_SINT16',
                    'TYPE_UINT16',
                    'TYPE_SINT32',
                    'TYPE_UINT32',
                    'TYPE_SINT64',
                    'TYPE_UINT64',
                    'TYPE_FLOAT',
                    'TYPE_VECTOR2',
                    'TYPE_VECTOR3',
                    'TYPE_VECTOR4',
                    'TYPE_QUATERNION',
                    'TYPE_MATRIX34',
                    'TYPE_MATRIX44',
                    'TYPE_POINTER',
                    'TYPE_ARRAY',
                    'TYPE_SIMPLE_ARRAY',
                    'TYPE_ENUM',
                    'TYPE_STRUCT',
                    'TYPE_FLAGS',
                    'TYPE_CSTRING',
                    'TYPE_STRING',
                    'TYPE_OBJECT_ID',
                    'TYPE_POSITION',
                    'TYPE_COLOR_BYTE',
                    'TYPE_COLOR_FLOAT',
                ],
                'fixed_rfl_overrides': {
                    '?rflClass@DetailMesh@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'DetailMesh', 'member_count': 2, 'parent': 0 },
                    '?rflClass@OffMeshLinkParameter@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'OffMeshLinkParameter', 'member_count': 1, 'parent': 0 },
                    '?rflClass@Partitioning@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Partitioning', 'member_count': 1, 'parent': 0 },
                    '?rflClass@Polygonization@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Polygonization', 'member_count': 3, 'parent': 0 },
                    '?rflClass@Rasterization@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Rasterization', 'member_count': 2, 'parent': 0 },
                    '?rflClass@Region@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Region', 'member_count': 2, 'parent': 0 },
                    '?rflClass@World@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'World', 'member_count': 2, 'parent': 0 },
                    '?rflClass@FxBrunetonSky@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxBrunetonSky', 'member_count': 19, 'parent': 0 },
                    '?rflClass@FxBrunetonSkyNight@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxBrunetonSkyNight', 'member_count': 8, 'parent': 0 },
                    '?rflClass@FxCloudBlendParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCloudBlendParameter', 'member_count': 4, 'parent': 0 },
                    '?rflClass@FxCloudProcedural@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCloudProcedural', 'member_count': 4, 'parent': 0 },
                    '?rflClass@FxCloudShadowParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCloudShadowParameter', 'member_count': 3, 'parent': 0 },
                    '?rflClass@FxCrepuscularRay@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCrepuscularRay', 'member_count': 4, 'parent': 0 },
                    '?rflClass@FxDensityParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDensityParameter', 'member_count': 19, 'parent': 0 },
                    '?rflClass@FxDensityLodParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDensityLodParameter', 'member_count': 5, 'parent': 0 },
                    '?rflClass@FxDensityDebugParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDensityDebugParameter', 'member_count': 14, 'parent': 0 },
                    '?rflClass@ColorDropout@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'ColorDropout', 'member_count': 6, 'parent': 0 },
                    '?rflClass@ColorShift@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'ColorShift', 'member_count': 4, 'parent': 0 },
                    '?rflClass@DebugScreenOption@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'DebugScreenOption', 'member_count': 10, 'parent': 0 },
                    '?rflClass@FxAntiAliasing@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxAntiAliasing', 'member_count': 3, 'parent': 0 },
                    '?rflClass@FxBloomParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxBloomParameter', 'member_count': 5, 'parent': 0 },
                    '?rflClass@FxCameraControlParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCameraControlParameter', 'member_count': 3, 'parent': 0 },
                    '?rflClass@FxChromaticAberrationParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxChromaticAberrationParameter', 'member_count': 9, 'parent': 0 },
                    '?rflClass@FxColorAccessibilityFilterParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxColorAccessibilityFilterParameter', 'member_count': 9, 'parent': 0 },
                    '?rflClass@FxColorContrastParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxColorContrastParameter', 'member_count': 17, 'parent': 0 },
                    '?rflClass@FxCyberSpaceStartNoiseParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCyberSpaceStartNoiseParameter', 'member_count': 11, 'parent': 0 },
                    '?rflClass@FxDOFParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDOFParameter', 'member_count': 22, 'parent': 0 },
                },
                'caption_string_addr': 0x1440B7710,
            },
            'xbox': {
                'sdk_env_var': 'SONIC_FRONTIERS_SDK_XBOX',
                'sdk_prefix': 'RangersSDK',
                'segments': {
                    'data': '.data',
                    'rdata': '.rdata',
                    'text': '.text',
                    'denuvoized_text': None,
                },
                'pass_allocator': True,
                'namespaces': {
                    'rfl': {
                #         'FxBloomParameter': ['needle', 'hh'],
                #         'FxDOFParameter': ['needle', 'hh'],
                #         'FxColorContrastParameter': ['needle', 'hh'],
                #         'FxToneMapParameter': ['needle', 'hh'],
                #         'FxCameraControlParameter': ['needle', 'hh'],
                #         'FxShadowMapParameter': ['needle', 'hh'],
                #         'FxShadowHeightMapParameter': ['needle', 'hh'],
                #         'FxVolumetricShadowParameter': ['needle', 'hh'],
                #         'FxScreenBlurParameter': ['needle', 'hh'],
                #         'FxSSAOParameter': ['needle', 'hh'],
                #         'FxSHLightFieldParameter': ['needle', 'hh'],
                #         'FxLightScatteringParameter': ['needle', 'hh'],
                #         'FxRLRParameter': ['needle', 'hh'],
                #         'FxSSGIParameter': ['needle', 'hh'],
                #         'FxPlanarReflectionParameter': ['needle', 'hh'],
                #         'FxOcclusionCapsuleParameter': ['needle', 'hh'],
                #         'FxGodrayParameter': ['needle', 'hh'],
                #         'FxScreenSpaceGodrayParameter': ['needle', 'hh'],
                #         'FxHeatHazeParameter': ['needle', 'hh'],
                #         'FxSceneEnvironmentParameter': ['needle', 'hh'],
                #         'FxRenderOption': ['needle', 'hh'],
                #         'FxSGGIParameter': ['needle', 'hh'],
                #         'FxTAAParameter': ['needle', 'hh'],
                #         'FxEffectParameter': ['needle', 'hh'],
                #         'FxAtmosphereParameter': ['needle', 'hh'],
                #         'FxDensityParameter': ['needle', 'hh'],
                #         'FxWindComputeParameter': ['needle', 'hh'],
                #         'FxGpuEnvironmentParameter': ['needle', 'hh'],
                #         'FxInteractiveWaveParameter': ['needle', 'hh'],
                #         'FxChromaticAberrationParameter': ['needle', 'hh'],
                #         'FxVignetteParameter': ['needle', 'hh'],
                #         'FxTerrainMaterialBlendingParameter': ['needle', 'hh'],
                #         'FxWeatherParameter': ['needle', 'hh'],
                #         'FxColorAccessibilityFilterParameter': ['needle', 'hh'],
                #         'FxCyberNoiseEffectParameter': ['needle', 'hh'],
                #         'FxCyberSpaceStartNoiseParameter': ['needle', 'hh'],
                #         'FxCyberNPCSSEffectRenderParameter': ['needle', 'hh'],
                #         'FxDentParameter': ['gfx', 'hh'],
                #         'FxFieldScanEffectRenderParameter': ['needle', 'hh'],
                #         'FxSeparableSSSParameter': ['needle', 'hh'],
                #         'FxRenderTargetSetting': ['gfx', 'hh'],
                #         'FxAntiAliasing': ['needle', 'hh'],
                #         'StageCommonAtmosphereParameter': ['gfx', 'hh'],
                #         'FxLODParameter': ['needle', 'hh'],
                #         'FxDetailParameter': ['needle', 'hh'],
                #         'FxDynamicResolutionParameter': ['needle', 'hh'],
                #         'FxPlanarProjectionShadowParameter': ['needle', 'hh'],
                #         'FxSunPosAngle': ['needle', 'hh'],
                #         'FxSunPosEarth': ['needle', 'hh'],
                #         'FxSun': ['needle', 'hh'],
                #         'FxMoon': ['needle', 'hh'],
                #         'FxSkyCommon': ['needle', 'hh'],
                #         'FxManualHeightFog': ['needle', 'hh'],
                #         'FxHeightFog': ['needle', 'hh'],
                #         'FxSebastienSky': ['needle', 'hh'],
                #         'FxBrunetonSky': ['needle', 'hh'],
                #         'FxBrunetonSkyNight': ['needle', 'hh'],
                #         'FxDensityWindParameter': ['needle', 'hh'],
                #         'FxTerrainParameter': ['needle', 'hh'],
                #         'FxDropParameter': ['needle', 'hh'],
                #         'FxPuddleParameter': ['needle', 'hh'],
                #         'FxRippleParameter': ['needle', 'hh'],
                #         'FxRainParameter': ['needle', 'hh'],
                #         'FxDistanceFogParameter': ['needle', 'hh'],
                #         'FxHeightFogParameter': ['needle', 'hh'],
                #         'FxFogParameter': ['needle', 'hh'],
                #         'FxInteractionDebugParameter': ['needle', 'hh'],
                #         'FxInteractionParameter': ['needle', 'hh'],
                #         'FxModelParameter': ['needle', 'hh'],
                #         'FxAutoExposureParameter': ['needle', 'hh'],
                #         'FxDirectionalRadialBlurParameter': ['needle', 'hh'],
                #         'FxFXAAParameter': ['needle', 'hh'],
                #         'FxGodrayVolumeTexture': ['needle', 'hh'],
                #         'FxHBAO_Parameter': ['needle', 'hh'],
                #         'FxHeightMapParameter': ['needle', 'hh'],
                #         'FxLightFieldMergeParameter': ['needle', 'hh'],
                #         'FxManualExposureParameter': ['needle', 'hh'],
                #         'FxPlanarProjectionShadowParameter': ['needle', 'hh'],
                #         'FxSMAAParameter': ['needle', 'hh'],
                #         'FxSSAO_Parameter': ['needle', 'hh'],
                #         'FxSSS_Parameter': ['needle', 'hh'],
                #         'FxSSGIDebugParameter': ['needle', 'hh'],
                #         'FxToneMapParameterFilmic': ['needle', 'hh'],
                #         'FxToneMapParameterGT': ['needle', 'hh'],
                #         'FxVfDepthParameter': ['needle', 'hh'],
                #         'FxVfImageCircleParameter': ['needle', 'hh'],
                #         'FxVfLineParameter': ['needle', 'hh'],
                #         'FxWindComputeDebugParameter': ['needle', 'hh'],
                #         'FxCloudBlendParameter': ['needle', 'hh'],
                #         'FxCloudProcedural': ['needle', 'hh'],
                #         'FxCloudShadowParameter': ['needle', 'hh'],
                #         'FxCrepuscularRay': ['needle', 'hh'],
                #         'FxDensityParameter': ['needle', 'hh'],
                #         'FxDensityLodParameter': ['needle', 'hh'],
                #         'FxDensityDebugParameter': ['needle', 'hh'],
                #         'ColorDropout': ['needle', 'hh'],
                #         'ColorShift': ['needle', 'hh'],
                #         'DebugScreenOption': ['needle', 'hh'],
                #         'FxAntiAliasing': ['needle', 'hh'],
                #         'FxBloomParameter': ['needle', 'hh'],
                #         'FxCameraControlParameter': ['needle', 'hh'],
                #         'FxChromaticAberrationParameter': ['needle', 'hh'],
                #         'FxColorAccessibilityFilterParameter': ['needle', 'hh'],
                #         'FxColorContrastParameter': ['needle', 'hh'],
                #         'FxCyberSpaceStartNoiseParameter': ['needle', 'hh'],
                #         'StageCommonTimeProgressParameter': ['gfx', 'hh'],
                #         'NeedleFxSceneConfig': ['needle', 'hh'],
                #         'NeedleFxParameter': ['needle', 'hh'],
                #         'NeedleFxSceneData': ['needle', 'hh'],
                    },
                    'resources': {
                #         'ResAtomConfig': ['snd', 'hh'],
                #         'ResAtomCueSheet': ['snd', 'hh'],
                #         'ResMirageLight': ['gfx', 'hh'],
                #         'ResMaterial': ['gfx', 'hh'],
                #         'ResTerrainModel': ['gfx', 'hh'],
                #         'ResModel': ['gfx', 'hh'],
                #         'ResComputeShader': ['gfnd', 'hh'],
                #         'ResFragmentShader': ['gfnd', 'hh'],
                #         'ResVertexShader': ['gfnd', 'hh'],
                #         'ResTexture': ['gfnd', 'hh'],
                #         'ResLevel': ['level', 'app'],
                #         'ResMasterLevel': ['level', 'app'],
                #         'ResBitmapFont': ['font', 'hh'],
                #         'ResScalableFontSet': ['font', 'hh'],
                #         'ResReflection': ['fnd', 'hh'],
                #         'Packfile': ['fnd', 'hh'],
                #         'ResEffect': ['eff', 'hh'],
                    },
                },
                'heuristics': {
                    'looks_like_instantiator': looks_like_instantiator_rangers,
                },
                'rfl_member_types': [
                    'TYPE_VOID',
                    'TYPE_BOOL',
                    'TYPE_SINT8',
                    'TYPE_UINT8',
                    'TYPE_SINT16',
                    'TYPE_UINT16',
                    'TYPE_SINT32',
                    'TYPE_UINT32',
                    'TYPE_SINT64',
                    'TYPE_UINT64',
                    'TYPE_FLOAT',
                    'TYPE_VECTOR2',
                    'TYPE_VECTOR3',
                    'TYPE_VECTOR4',
                    'TYPE_QUATERNION',
                    'TYPE_MATRIX34',
                    'TYPE_MATRIX44',
                    'TYPE_POINTER',
                    'TYPE_ARRAY',
                    'TYPE_SIMPLE_ARRAY',
                    'TYPE_ENUM',
                    'TYPE_STRUCT',
                    'TYPE_FLAGS',
                    'TYPE_CSTRING',
                    'TYPE_STRING',
                    'TYPE_OBJECT_ID',
                    'TYPE_POSITION',
                    'TYPE_COLOR_BYTE',
                    'TYPE_COLOR_FLOAT',
                ],
                'fixed_rfl_overrides': {
                    # '?rflClass@DetailMesh@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'DetailMesh', 'member_count': 2, 'parent': 0 },
                    # '?rflClass@OffMeshLinkParameter@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'OffMeshLinkParameter', 'member_count': 1, 'parent': 0 },
                    # '?rflClass@Partitioning@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Partitioning', 'member_count': 1, 'parent': 0 },
                    # '?rflClass@Polygonization@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Polygonization', 'member_count': 3, 'parent': 0 },
                    # '?rflClass@Rasterization@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Rasterization', 'member_count': 2, 'parent': 0 },
                    # '?rflClass@Region@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'Region', 'member_count': 2, 'parent': 0 },
                    # '?rflClass@World@heur@rfl@@2VRflClass@fnd@hh@@B': { 'name': 'World', 'member_count': 2, 'parent': 0 },
                    # '?rflClass@FxBrunetonSky@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxBrunetonSky', 'member_count': 19, 'parent': 0 },
                    # '?rflClass@FxBrunetonSkyNight@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxBrunetonSkyNight', 'member_count': 8, 'parent': 0 },
                    # '?rflClass@FxCloudBlendParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCloudBlendParameter', 'member_count': 4, 'parent': 0 },
                    # '?rflClass@FxCloudProcedural@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCloudProcedural', 'member_count': 4, 'parent': 0 },
                    # '?rflClass@FxCloudShadowParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCloudShadowParameter', 'member_count': 3, 'parent': 0 },
                    # '?rflClass@FxCrepuscularRay@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCrepuscularRay', 'member_count': 4, 'parent': 0 },
                    # '?rflClass@FxDensityParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDensityParameter', 'member_count': 19, 'parent': 0 },
                    # '?rflClass@FxDensityLodParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDensityLodParameter', 'member_count': 5, 'parent': 0 },
                    # '?rflClass@FxDensityDebugParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDensityDebugParameter', 'member_count': 14, 'parent': 0 },
                    # '?rflClass@ColorDropout@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'ColorDropout', 'member_count': 6, 'parent': 0 },
                    # '?rflClass@ColorShift@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'ColorShift', 'member_count': 4, 'parent': 0 },
                    # '?rflClass@DebugScreenOption@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'DebugScreenOption', 'member_count': 10, 'parent': 0 },
                    # '?rflClass@FxAntiAliasing@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxAntiAliasing', 'member_count': 3, 'parent': 0 },
                    # '?rflClass@FxBloomParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxBloomParameter', 'member_count': 5, 'parent': 0 },
                    # '?rflClass@FxCameraControlParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCameraControlParameter', 'member_count': 3, 'parent': 0 },
                    # '?rflClass@FxChromaticAberrationParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxChromaticAberrationParameter', 'member_count': 9, 'parent': 0 },
                    # '?rflClass@FxColorAccessibilityFilterParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxColorAccessibilityFilterParameter', 'member_count': 9, 'parent': 0 },
                    # '?rflClass@FxColorContrastParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxColorContrastParameter', 'member_count': 17, 'parent': 0 },
                    # '?rflClass@FxCyberSpaceStartNoiseParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCyberSpaceStartNoiseParameter', 'member_count': 11, 'parent': 0 },
                    # '?rflClass@FxDOFParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDOFParameter', 'member_count': 22, 'parent': 0 },
                },
                'caption_string_addr': 0x1412B7E80,
            }
        },
    },
    'wars': {
        'latest': {
            'steam': {
                'sdk_env_var': 'SONIC_FORCES_SDK',
                'sdk_prefix': 'WarsSDK',
                'segments': {
                    'data': '.srdata',
                    'rdata': '.tls',
                    'text': '.xtext',
                    'denuvoized_text': '.arch',
                },
                'pass_allocator': False,
                'namespaces': {
                    'rfl': {
                        'FxBloomParameter': ['hh'],
                        'FxColorContrastParameter': ['hh'],
                        'FxDOFParameter': ['hh'],
                        'FxExposureParameter': ['hh'],
                        'FxToneMapParameter': ['hh'],
                        'FxShadowMapParameter': ['hh'],
                        'FxLightFieldParameter': ['hh'],
                        'FxLightScatteringParameter': ['hh'],
                        'FxOcclusionCapsuleParameter': ['hh'],
                        'FxRLRParameter': ['hh'],
                        'FxGodrayParameter': ['hh'],
                        'FxScreenSpaceGodrayParameter': ['hh'],
                        'FxEffectParameter': ['hh'],
                        'FxDebugScreenOption': ['hh'],
                        'FxRenderOption': ['hh'],
                        'FxHDROption': ['hh'],
                        'FxSGGIParameter': ['hh'],
                        'FxSSAOParameter': ['hh'],
                        'FxSHLightFieldParameter': ['hh'],
                        'FxScreenBlurParameter': ['hh'],
                        'FxHeatHazeParameter': ['hh'],
                        'FxSceneEnvironmentParameter': ['hh'],
                        'FxTAAParameter': ['hh'],
                        'NeedleFxParameter': ['hh'],
                        'FxRenderTargetSetting': ['hh'],
                        'FxAntiAliasing': ['hh'],
                        'NeedleFxSceneConfig': ['hh'],
                        'StageCommonParameter': ['hh'],
                        'StageCameraParameter': ['hh'],
                        'StageConfig': ['hh'],
                        'NeedleFxSceneData': ['hh'],
                    },
                    'resources': {
                        'ResAtomConfig': ['snd', 'hh'],
                        'ResAtomCueSheet': ['snd', 'hh'],
                        'ResMirageLight': ['gfx', 'hh'],
                        'ResMaterial': ['gfx', 'hh'],
                        'ResTerrainModel': ['gfx', 'hh'],
                        'ResModel': ['gfx', 'hh'],
                        'ResComputeShader': ['gfnd', 'hh'],
                        'ResFragmentShader': ['gfnd', 'hh'],
                        'ResVertexShader': ['gfnd', 'hh'],
                        'ResTexture': ['gfnd', 'hh'],
                        'ResLevel': ['level', 'app'],
                        'ResMasterLevel': ['level', 'app'],
                        'ResBitmapFont': ['font', 'hh'],
                        'ResScalableFontSet': ['font', 'hh'],
                        'ResReflection': ['fnd', 'hh'],
                        'Packfile': ['fnd', 'hh'],
                        'ResEffect': ['eff', 'hh'],
                    },
                },
                'resource_namespaces': {},
                'allocator_addresses': (0x14071B3A0, 0x1406B79B0, 0x14071B410),
                'heuristics': {
                    'looks_like_instantiator': looks_like_instantiator_wars,
                },
                'rfl_member_types': [
                    'TYPE_VOID',
                    'TYPE_BOOL',
                    'TYPE_SINT8',
                    'TYPE_UINT8',
                    'TYPE_SINT16',
                    'TYPE_UINT16',
                    'TYPE_SINT32',
                    'TYPE_UINT32',
                    'TYPE_SINT64',
                    'TYPE_UINT64',
                    'TYPE_FLOAT',
                    'TYPE_VECTOR2',
                    'TYPE_VECTOR3',
                    'TYPE_VECTOR4',
                    'TYPE_QUATERNION',
                    'TYPE_MATRIX34',
                    'TYPE_MATRIX44',
                    'TYPE_POINTER',
                    'TYPE_ARRAY',
                    'TYPE_OLD_ARRAY',
                    'TYPE_SIMPLE_ARRAY',
                    'TYPE_ENUM',
                    'TYPE_STRUCT',
                    'TYPE_FLAGS',
                    'TYPE_CSTRING',
                    'TYPE_STRING',
                    'TYPE_OBJECT_ID',
                    'TYPE_POSITION',
                    'TYPE_COLOR_BYTE',
                    'TYPE_COLOR_FLOAT',
                ],
                'fixed_rfl_overrides': {},
            },
        },
    },
    
    'miller': {
        '1.00': {
            'steam': {
                'sdk_env_var': 'MILLER_SDK',
                'sdk_prefix': 'MillerSDK',
                'segments': {
                    'data': '.rtti',
                    'rdata': '.text',
                    'text': '.shared',
                    'denuvoized_text': '.debug$P',
                },
                'pass_allocator': True,
                'heuristics': {
                    'looks_like_instantiator': looks_like_instantiator_rangers,
                },
                'namespaces': {
                    'rfl': {
                        'FxBloomParameter': ['needle', 'hh'],
                        'FxDOFParameter': ['needle', 'hh'],
                        'FxColorContrastParameter': ['needle', 'hh'],
                        'FxToneMapParameter': ['needle', 'hh'],
                        'FxCameraControlParameter': ['needle', 'hh'],
                        'FxShadowMapParameter': ['needle', 'hh'],
                        'FxShadowHeightMapParameter': ['needle', 'hh'],
                        'FxVolumetricShadowParameter': ['needle', 'hh'],
                        'FxScreenBlurParameter': ['needle', 'hh'],
                        'FxSSAOParameter': ['needle', 'hh'],
                        'FxSHLightFieldParameter': ['needle', 'hh'],
                        'FxLightScatteringParameter': ['needle', 'hh'],
                        'FxRLRParameter': ['needle', 'hh'],
                        'FxSSGIParameter': ['needle', 'hh'],
                        'FxPlanarReflectionParameter': ['needle', 'hh'],
                        'FxOcclusionCapsuleParameter': ['needle', 'hh'],
                        'FxGodrayParameter': ['needle', 'hh'],
                        'FxScreenSpaceGodrayParameter': ['needle', 'hh'],
                        'FxHeatHazeParameter': ['needle', 'hh'],
                        'FxSceneEnvironmentParameter': ['needle', 'hh'],
                        'FxRenderOption': ['needle', 'hh'],
                        'FxSGGIParameter': ['needle', 'hh'],
                        'FxTAAParameter': ['needle', 'hh'],
                        'FxEffectParameter': ['needle', 'hh'],
                        'FxAtmosphereParameter': ['needle', 'hh'],
                        'FxDensityParameter': ['needle', 'hh'],
                        'FxWindComputeParameter': ['needle', 'hh'],
                        'FxGpuEnvironmentParameter': ['needle', 'hh'],
                        'FxInteractiveWaveParameter': ['needle', 'hh'],
                        'FxChromaticAberrationParameter': ['needle', 'hh'],
                        'FxVignetteParameter': ['needle', 'hh'],
                        'FxTerrainMaterialBlendingParameter': ['needle', 'hh'],
                        'FxWeatherParameter': ['needle', 'hh'],
                        'FxColorAccessibilityFilterParameter': ['needle', 'hh'],
                        'FxCyberNoiseEffectParameter': ['needle', 'hh'],
                        'FxCyberSpaceStartNoiseParameter': ['needle', 'hh'],
                        'FxCyberNPCSSEffectRenderParameter': ['needle', 'hh'],
                        'FxDentParameter': ['gfx', 'hh'],
                        'FxFieldScanEffectRenderParameter': ['needle', 'hh'],
                        'FxSeparableSSSParameter': ['needle', 'hh'],
                        'FxRenderTargetSetting': ['gfx', 'hh'],
                        'FxAntiAliasing': ['needle', 'hh'],
                        'StageCommonAtmosphereParameter': ['gfx', 'hh'],
                        'FxLODParameter': ['needle', 'hh'],
                        'FxDetailParameter': ['needle', 'hh'],
                        'FxDynamicResolutionParameter': ['needle', 'hh'],
                        'FxPlanarProjectionShadowParameter': ['needle', 'hh'],
                        'FxSunPosAngle': ['needle', 'hh'],
                        'FxSunPosEarth': ['needle', 'hh'],
                        'FxSun': ['needle', 'hh'],
                        'FxMoon': ['needle', 'hh'],
                        'FxSkyCommon': ['needle', 'hh'],
                        'FxManualHeightFog': ['needle', 'hh'],
                        'FxHeightFog': ['needle', 'hh'],
                        'FxSebastienSky': ['needle', 'hh'],
                        'FxBrunetonSky': ['needle', 'hh'],
                        'FxBrunetonSkyNight': ['needle', 'hh'],
                        'FxDensityWindParameter': ['needle', 'hh'],
                        'FxTerrainParameter': ['needle', 'hh'],
                        'FxDropParameter': ['needle', 'hh'],
                        'FxPuddleParameter': ['needle', 'hh'],
                        'FxRippleParameter': ['needle', 'hh'],
                        'FxRainParameter': ['needle', 'hh'],
                        'FxDistanceFogParameter': ['needle', 'hh'],
                        'FxHeightFogParameter': ['needle', 'hh'],
                        'FxFogParameter': ['needle', 'hh'],
                        'FxInteractionDebugParameter': ['needle', 'hh'],
                        'FxInteractionParameter': ['needle', 'hh'],
                        'FxModelParameter': ['needle', 'hh'],
                        'FxAutoExposureParameter': ['needle', 'hh'],
                        'FxDirectionalRadialBlurParameter': ['needle', 'hh'],
                        'FxFXAAParameter': ['needle', 'hh'],
                        'FxGodrayVolumeTexture': ['needle', 'hh'],
                        'FxHBAO_Parameter': ['needle', 'hh'],
                        'FxHeightMapParameter': ['needle', 'hh'],
                        'FxLightFieldMergeParameter': ['needle', 'hh'],
                        'FxManualExposureParameter': ['needle', 'hh'],
                        'FxPlanarProjectionShadowParameter': ['needle', 'hh'],
                        'FxSMAAParameter': ['needle', 'hh'],
                        'FxSSAO_Parameter': ['needle', 'hh'],
                        'FxSSS_Parameter': ['needle', 'hh'],
                        'FxSSGIDebugParameter': ['needle', 'hh'],
                        'FxToneMapParameterFilmic': ['needle', 'hh'],
                        'FxToneMapParameterGT': ['needle', 'hh'],
                        'FxVfDepthParameter': ['needle', 'hh'],
                        'FxVfImageCircleParameter': ['needle', 'hh'],
                        'FxVfLineParameter': ['needle', 'hh'],
                        'FxWindComputeDebugParameter': ['needle', 'hh'],
                        'FxCloudBlendParameter': ['needle', 'hh'],
                        'FxCloudProcedural': ['needle', 'hh'],
                        'FxCloudShadowParameter': ['needle', 'hh'],
                        'FxCrepuscularRay': ['needle', 'hh'],
                        'FxDensityParameter': ['needle', 'hh'],
                        'FxDensityLodParameter': ['needle', 'hh'],
                        'FxDensityDebugParameter': ['needle', 'hh'],
                        'ColorDropout': ['needle', 'hh'],
                        'ColorShift': ['needle', 'hh'],
                        'DebugScreenOption': ['needle', 'hh'],
                        'FxAntiAliasing': ['needle', 'hh'],
                        'FxBloomParameter': ['needle', 'hh'],
                        'FxCameraControlParameter': ['needle', 'hh'],
                        'FxChromaticAberrationParameter': ['needle', 'hh'],
                        'FxColorAccessibilityFilterParameter': ['needle', 'hh'],
                        'FxColorContrastParameter': ['needle', 'hh'],
                        'FxCyberSpaceStartNoiseParameter': ['needle', 'hh'],
                        'FxTimeStopParameter': ['needle', 'hh'],
                        'FxCullingSettings': ['needle', 'hh'],
                        'FxEffectSettings': ['needle', 'hh'],
                        'FxInShadowShadowScaleSettings': ['needle', 'hh'],
                        'FxStaticSkyDomeParameter': ['needle', 'hh'],
                        'FxParameter': ['needle', 'hh'],
                        'StageCommonTimeProgressParameter': ['gfx', 'hh'],
                        'PerformanceSetting': ['gfx', 'hh'],
                        'NeedleFxSceneConfig': ['needle', 'hh'],
                        'NeedleFxParameter': ['needle', 'hh'],
                        'NeedleFxSceneData': ['needle', 'hh'],

                        'PlayLog': ['save', 'app'],
                        'PlayStatsSummary': ['save', 'app'],
                        'PlayStatsData': ['save', 'app'],
                        'PlayStats': ['save', 'app'],
                        'StageData': ['save', 'app'],
                        'WorldFlagData': ['save', 'app'],
                        'AddContentDataGame': ['save', 'app'],
                        'RankingData': ['save', 'app'],
                        'AddContentDataSystem': ['save', 'app'],
                        'CharacterData': ['save', 'app'],
                        'UnlockData': ['save', 'app'],
                        'CollectionData': ['save', 'app'],
                        'CRMContainerData': ['save', 'app'],
                        'FlagContainerData': ['save', 'app'],
                        'HeaderData': ['save', 'app'],
                        'GamePlayData': ['save', 'app'],
                        'WhitespaceStageData': ['save', 'app'],
                        'StageContainerData': ['save', 'app'],
                        'UnlockQAData': ['save', 'app'],
                        'QAData': ['save', 'app'],
                        'WorldFlagContainerData': ['save', 'app'],
                        'StatValue': ['save', 'app'],
                        'StatsContainerData': ['save', 'app'],
                        'GameData': ['save', 'app'],
                        'NoSaveData': ['save', 'app'],
                        'OptionAudioData': ['save', 'app'],
                        'OptionCameraData': ['save', 'app'],
                        'OptionControlsData': ['save', 'app'],
                        'OptionGamePlayData': ['save', 'app'],
                        'OptionGraphicsData': ['save', 'app'],
                        'PlayLogCoordData': ['save', 'app'],
                        'PlayLogEventData': ['save', 'app'],
                        'PlayLogData': ['save', 'app'],
                        'RankingContainerData': ['save', 'app'],
                        'SystemData': ['save', 'app'],

                        'PlayerParamOffensive': ['player', 'app'],
                        'PlayerParamDefensive': ['player', 'app'],
                        'PlayerParamAttackCommon': ['player', 'app'],
                        'PlayerParamAttackData': ['player', 'app'],
                        'PlayerParamAttack': ['player', 'app'],
                        'PlayerParamAttackCollider': ['player', 'app'],
                        'PlayerParamStompingAttack': ['player', 'app'],
                        'PlayerParamBehind': ['player', 'app'],
                        'PlayerParamWaterAct': ['player', 'app'],
                        'PlayerParamBaseJump': ['player', 'app'],
                        'PlayerParamBallMove': ['player', 'app'],
                        'PlayerParamLocusData': ['player', 'app'],
                        'PlayerParamLocus': ['player', 'app'],
                        'PlayerParamSlingshot': ['player', 'app'],
                        'PlayerParamAuraTrain': ['player', 'app'],
                        'PlayerParamLevel': ['player', 'app'],
                        'PlayerParamBarrierWall': ['player', 'app'],
                        'PlayerParamWarpAttack': ['player', 'app'],
                        'PlayerParamDBlowRush': ['player', 'app'],
                        'PlayerParamDBlowRushFinish': ['player', 'app'],
                        'PlayerParamDBlowOff': ['player', 'app'],
                        'PlayerParamDBlowUp': ['player', 'app'],
                        'PlayerParamDBlowDown': ['player', 'app'],
                        'PlayerParamChaosSpear': ['player', 'app'],
                        'PlayerParamChaosSpearData': ['player', 'app'],
                        'PlayerParamMirageEffect': ['player', 'app'],
                        'PlayerParamFacingData': ['player', 'app'],
                        'PlayerParamFacing': ['player', 'app'],
                        'PlayerParamEtc': ['player', 'app'],
                        'CommonPackage': ['player', 'app'],
                        'PlayerParamCommon': ['player', 'app'],
                        'PlayerParamSpeedData': ['player', 'app'],
                        'PlayerParamSpeedAcceleData': ['player', 'app'],
                        'PlayerParamSpeed': ['player', 'app'],
                        'PlayerParamRotation': ['player', 'app'],
                        'PlayerParamRunning': ['player', 'app'],
                        'PlayerParamBalanceData': ['player', 'app'],
                        'PlayerParamBalance': ['player', 'app'],
                        'PlayerParamBrake': ['player', 'app'],
                        'PlayerParamTurn': ['player', 'app'],
                        'PlayerParamJump': ['player', 'app'],
                        'PlayerParamLocalJump': ['player', 'app'],
                        'PlayerParamDWingJump': ['player', 'app'],
                        'PlayerParamJumpSpeed': ['player', 'app'],
                        'PlayerParamDoubleJump': ['player', 'app'],
                        'PlayerParamDWingDoubleJump': ['player', 'app'],
                        'PlayerParamFall': ['player', 'app'],
                        'PlayerParamSpringFall': ['player', 'app'],
                        'PlayerParamHomingRebound': ['player', 'app'],
                        'PlayerParamDamageCommon': ['player', 'app'],
                        'PlayerParamDamageNormal': ['player', 'app'],
                        'PlayerParamDamageTurnBack': ['player', 'app'],
                        'PlayerParamDamageBlowOff': ['player', 'app'],
                        'PlayerParamDamageGuarded': ['player', 'app'],
                        'PlayerParamDamageRunning': ['player', 'app'],
                        'PlayerParamDamageQuake': ['player', 'app'],
                        'PlayerParamDamageLava': ['player', 'app'],
                        'PlayerParamDamage': ['player', 'app'],
                        'PlayerParamDeadNormal': ['player', 'app'],
                        'PlayerParamDead': ['player', 'app'],
                        'PlayerParamSliding': ['player', 'app'],
                        'PlayerParamStomping': ['player', 'app'],
                        'PlayerParamGrind': ['player', 'app'],
                        'PlayerParamFallSlope': ['player', 'app'],
                        'PlayerParamFallFlip': ['player', 'app'],
                        'PlayerParamTumble': ['player', 'app'],
                        'PlayerParamSpinAttack': ['player', 'app'],
                        'PlayerParamHomingAttackData': ['player', 'app'],
                        'PlayerParamHomingBounceData': ['player', 'app'],
                        'PlayerParamHomingAttack': ['player', 'app'],
                        'PlayerParamHitEnemy': ['player', 'app'],
                        'SpeedParam': ['player', 'app'],
                        'PlayerParamDiving': ['player', 'app'],
                        'PlayerParamFan': ['player', 'app'],
                        'PlayerParamStorm': ['player', 'app'],
                        'PlayerParamCloudJump': ['player', 'app'],
                        'PlayerParamAirTrick': ['player', 'app'],
                        'PlayerParamDrift': ['player', 'app'],
                        'PlayerParamDriftAir': ['player', 'app'],
                        'PlayerParamDriftDash': ['player', 'app'],
                        'PlayerParamDropDash': ['player', 'app'],
                        'PlayerParamBounceJump': ['player', 'app'],
                        'PlayerParamLightDash': ['player', 'app'],
                        'PlayerParamBackflip': ['player', 'app'],
                        'PlayerParamSquatMove': ['player', 'app'],
                        'PlayerParamSlowMove': ['player', 'app'],
                        'PlayerParamSpinDash': ['player', 'app'],
                        'PlayerParamSpin': ['player', 'app'],
                        'PlayerParamWallMove': ['player', 'app'],
                        'PlayerParamWallJump': ['player', 'app'],
                        'PlayerParamClimbing': ['player', 'app'],
                        'PlayerParamSlideDown': ['player', 'app'],
                        'PlayerParamBoarding': ['player', 'app'],
                        'PlayerParamSlowWalk': ['player', 'app'],
                        'PlayerParamJog': ['player', 'app'],
                        'PlayerParamSkate': ['player', 'app'],
                        'PlayerParamShiftRun': ['player', 'app'],
                        'PlayerParamBoostCamera': ['player', 'app'],
                        'PlayerParamBoostBlur': ['player', 'app'],
                        'PlayerParamBoost': ['player', 'app'],
                        'PlayerParamAirBoost': ['player', 'app'],
                        'PlayerParamAutorun': ['player', 'app'],
                        'PlayerParamSlider': ['player', 'app'],
                        'PlayerParamSideStep': ['player', 'app'],
                        'PlayerParamSideStep2': ['player', 'app'],
                        'PlayerParamQuickStep': ['player', 'app'],
                        'PlayerParamParry': ['player', 'app'],
                        'PlayerParamAvoidData': ['player', 'app'],
                        'PlayerParamAvoid': ['player', 'app'],
                        'PlayerParamTimeStop': ['player', 'app'],
                        'PlayerParamPhotonDash': ['player', 'app'],
                        'PlayerParamJumpDash': ['player', 'app'],
                        'PlayerParamRunOnWater': ['player', 'app'],
                        'PlayerParamDBlow': ['player', 'app'],
                        'PlayerParamDSurf': ['player', 'app'],
                        'PlayerParamDSurfSpinParam': ['player', 'app'],
                        'PlayerParamDSurfSpin': ['player', 'app'],
                        'PlayerParamDSurfSpinSV': ['player', 'app'],
                        'PlayerParamDAmoeba': ['player', 'app'],
                        'PlayerParamDAmoebaAir': ['player', 'app'],
                        'PlayerParamDAmoebaHoming': ['player', 'app'],
                        'PlayerParamDWingGuardParam': ['player', 'app'],
                        'PlayerParamDWingGuard': ['player', 'app'],
                        'PlayerParamDWingFlinch': ['player', 'app'],
                        'PlayerParamWaterFlow': ['player', 'app'],
                        'PlayerParamSlalomStep': ['player', 'app'],
                        'PlayerParamGliding2': ['player', 'app'],
                        'PlayerParamChaosSpearAir': ['player', 'app'],
                        'ModePackage': ['player', 'app'],
                        'PlayerParamAerialFinish': ['player', 'app'],
                        'PlayerParameters': ['player', 'app'],
                        'PlayerParamLowAltitudeJump': ['player', 'app'],
                        'PlayerParamGliding': ['player', 'app'],
                        'PlayerCameraParameter': ['player', 'app'],
                        'PlayerCameraSetParameter': ['player', 'app'],
                        'PlayerCameraSetParameters': ['player', 'app'],

                        'AmbBaseNoiseParameter': ['snd', 'app'],
                        'AmbInfo': ['snd', 'app'],
                        'AmbNearPointParameter': ['snd', 'app'],
                        'AmbRelativeWindParameter': ['snd', 'app'],
                        'AmbRiverParameter_Multiple3D': ['snd', 'app'],
                        'AmbRiverParameter_Nearest': ['snd', 'app'],
                        'AmbSoundParameter': ['snd', 'app'],
                        'AisacChangeInfo': ['snd', 'app'],
                        'AisacChangeInfoList': ['snd', 'app'],
                        'BGMInfo': ['snd', 'app'],
                        'BGMTransitInfo': ['snd', 'app'],
                        'BGMSceneInfo': ['snd', 'app'],
                        'BGMInfoParameter': ['snd', 'app'],
                        'BGMVolumeChangeInfo': ['snd', 'app'],
                        'BGMVolumeChangeInfoList': ['snd', 'app'],
                        'SoundCommonParameter': ['snd', 'app'],
                    },
                    'resources': {
                        'ResAtomConfig': ['snd', 'hh'],
                        'ResAtomCueSheet': ['snd', 'hh'],
                        'ResMirageLight': ['gfx', 'hh'],
                        'ResMaterial': ['gfx', 'hh'],
                        'ResTerrainModel': ['gfx', 'hh'],
                        'ResModel': ['gfx', 'hh'],
                        'ResComputeShader': ['gfnd', 'hh'],
                        'ResFragmentShader': ['gfnd', 'hh'],
                        'ResVertexShader': ['gfnd', 'hh'],
                        'ResTexture': ['gfnd', 'hh'],
                        'ResLevel': ['level', 'app'],
                        'ResMasterLevel': ['level', 'app'],
                        'ResBitmapFont': ['font', 'hh'],
                        'ResScalableFontSet': ['font', 'hh'],
                        'ResReflection': ['fnd', 'hh'],
                        'Packfile': ['fnd', 'hh'],
                        'ResEffect': ['eff', 'hh'],
                        'ResObjectWorld': ['game', 'hh'],
                    },
                },
                'fixed_rfl_enum_assignments': {
                    0x1428EAC10: 0x14129C280,
                    0x1428EB300: 0x1412A0200,
                    0x1428EB480: 0x1412A0600,
                    0x1428ED6A0: 0x1412AB310,
                    0x1428EDE20: 0x1412ADB90,
                    0x1428EAD60: 0x14129C298,
                    0x1428EB3F0: 0x1412A0218,
                    0x1428EB4B0: 0x1412A0618,
                    0x1428ED6D0: 0x1412AB328,
                    0x1428EDE50: 0x1412ADBA8,
                    0x1428EB420: 0x1412A0230,
                    0x1428ED700: 0x1412AB340,
                    0x1428EB450: 0x1412A0248,
                },
                'fixed_rfl_overrides': {
                    '?rflClass@enable@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'enable', 'parent': 0, 'class_size': 0, 'enum_count': 0, 'member_count': 1091802088, 'name_hash': 1093327760 },
                    '?rflClass@SwayParamNodeCollision@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'SwayParamNodeCollision', 'parent': 0, 'class_size': 768, 'enum_count': 0, 'member_count': 1, 'name_hash': 3526391325 },
                    '?rflClass@DetailMesh@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'DetailMesh', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 2, 'name_hash': 1164494013 },
                    '?rflClass@Filtering@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'Filtering', 'parent': 0, 'class_size': 3, 'enum_count': 0, 'member_count': 3, 'name_hash': 2645942041 },
                    '?rflClass@Rasterization@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'Rasterization', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 2, 'name_hash': 1164494013 },
                    '?rflClass@FxCullingSettings@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCullingSettings', 'parent': 0, 'class_size': 16, 'enum_count': 0, 'member_count': 4, 'name_hash': 46030037 },
                    '?rflClass@FxEffectSettings@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxEffectSettings', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 2, 'name_hash': 1164494013 },
                    '?rflClass@FxInShadowShadowScaleSettings@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxInShadowShadowScaleSettings', 'parent': 0, 'class_size': 12, 'enum_count': 0, 'member_count': 3, 'name_hash': 1589085337 },
                    '?rflClass@FxParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxParameter', 'parent': 0, 'class_size': 1184, 'enum_count': 0, 'member_count': 17, 'name_hash': 1016710140 },
                    '?rflClass@PSOCache@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'PSOCache', 'parent': 0, 'class_size': 408, 'enum_count': 1, 'member_count': 17, 'name_hash': 3886011963 },
                    '?rflClass@FxCloudProcedural@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxCloudProcedural', 'parent': 0, 'class_size': 64, 'enum_count': 0, 'member_count': 4, 'name_hash': 1017563305 },
                    '?rflClass@FxManualHeightFog@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxManualHeightFog', 'parent': 0, 'class_size': 32, 'enum_count': 0, 'member_count': 2, 'name_hash': 2863518599 },
                    '?rflClass@FxMoon@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxMoon', 'parent': 0, 'class_size': 1, 'enum_count': 1, 'member_count': 1, 'name_hash': 1572082945 },
                    '?rflClass@FxSebastienSky@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxSebastienSky', 'parent': 0, 'class_size': 144, 'enum_count': 0, 'member_count': 16, 'name_hash': 143126034 },
                    '?rflClass@FxSkyCommon@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxSkyCommon', 'parent': 0, 'class_size': 16, 'enum_count': 1, 'member_count': 4, 'name_hash': 3521670821 },
                    '?rflClass@FxStaticSkyDomeParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxStaticSkyDomeParameter', 'parent': 0, 'class_size': 12, 'enum_count': 1, 'member_count': 4, 'name_hash': 963229589 },
                    '?rflClass@FxSunPosAngle@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxSunPosAngle', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 2, 'name_hash': 1164494013 },
                    '?rflClass@FxSunPosEarth@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxSunPosEarth', 'parent': 0, 'class_size': 32, 'enum_count': 0, 'member_count': 8, 'name_hash': 1112544645 },
                    '?rflClass@FxDensityParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDensityParameter', 'parent': 0, 'class_size': 268, 'enum_count': 2, 'member_count': 19, 'name_hash': 1635307703 },
                    '?rflClass@FxLightScatteringParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxLightScatteringParameter', 'parent': 0, 'class_size': 96, 'enum_count': 0, 'member_count': 9, 'name_hash': 662203819 },
                    '?rflClass@FxDistanceFogParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDistanceFogParameter', 'parent': 0, 'class_size': 16, 'enum_count': 0, 'member_count': 4, 'name_hash': 3551592869 },
                    '?rflClass@FxDynamicResolutionParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxDynamicResolutionParameter', 'parent': 0, 'class_size': 40, 'enum_count': 1, 'member_count': 10, 'name_hash': 1479531677 },
                    '?rflClass@FxInteractionDebugParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxInteractionDebugParameter', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 3, 'name_hash': 2624500697 },
                    '?rflClass@DebugScreenOption@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'DebugScreenOption', 'parent': 0, 'class_size': 24, 'enum_count': 4, 'member_count': 10, 'name_hash': 417691709 },
                    '?rflClass@FxAntiAliasing@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxAntiAliasing', 'parent': 0, 'class_size': 8, 'enum_count': 2, 'member_count': 3, 'name_hash': 2624500697 },
                    '?rflClass@FxHBAO_Parameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxHBAO_Parameter', 'parent': 0, 'class_size': 28, 'enum_count': 0, 'member_count': 8, 'name_hash': 2411552773 },
                    '?rflClass@FxLightFieldMergeParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxLightFieldMergeParameter', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 2, 'name_hash': 4215049549 },
                    '?rflClass@FxManualExposureParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxManualExposureParameter', 'parent': 0, 'class_size': 4, 'enum_count': 0, 'member_count': 1, 'name_hash': 237661169 },
                    '?rflClass@FxRenderOption@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxRenderOption', 'parent': 0, 'class_size': 592, 'enum_count': 6, 'member_count': 30, 'name_hash': 4136992561 },
                    '?rflClass@FxRenderTargetSetting@gfx@hh@@2VRflClass@fnd@3@B': { 'name': 'FxRenderTargetSetting', 'parent': 0, 'class_size': 12, 'enum_count': 1, 'member_count': 3, 'name_hash': 2833222358 },
                    '?rflClass@FxSceneEnvironmentParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxSceneEnvironmentParameter', 'parent': 0, 'class_size': 96, 'enum_count': 0, 'member_count': 14, 'name_hash': 272304859 },
                    '?rflClass@FxSSAOParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxSSAOParameter', 'parent': 0, 'class_size': 112, 'enum_count': 3, 'member_count': 8, 'name_hash': 2584488613 },
                    '?rflClass@FxVfLineParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxVfLineParameter', 'parent': 0, 'class_size': 20, 'enum_count': 0, 'member_count': 5, 'name_hash': 2882690497 },
                    '?rflClass@NeedleFxParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'NeedleFxParameter', 'parent': 0, 'class_size': 5008, 'enum_count': 0, 'member_count': 42, 'name_hash': 0 },
                    '?rflClass@StageCommonParameter@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'StageCommonParameter', 'parent': 0, 'class_size': 12, 'enum_count': 0, 'member_count': 3, 'name_hash': 1589085337 },
                    '?rflClass@StageConfig@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'StageConfig', 'parent': 0, 'class_size': 88, 'enum_count': 0, 'member_count': 3, 'name_hash': 1061673033 },
                    '?rflClass@StageTerrainPrecisionParameter@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'StageTerrainPrecisionParameter', 'parent': 0, 'class_size': 4, 'enum_count': 0, 'member_count': 1, 'name_hash': 237661169 },
                    '?rflClass@FxPuddleParameter@needle@hh@@2VRflClass@fnd@3@B': { 'name': 'FxPuddleParameter', 'parent': 0, 'class_size': 24, 'enum_count': 0, 'member_count': 6, 'name_hash': 168237453 },
                    '?rflClass@GOCActivatorSpawner@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'GOCActivatorSpawner', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 2, 'name_hash': 1164494013 },
                    '?rflClass@DecoBlurParam@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'DecoBlurParam', 'parent': 0, 'class_size': 4, 'enum_count': 0, 'member_count': 1, 'name_hash': 2422601022 },
                    '?rflClass@DecoDropShadowParam@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'DecoDropShadowParam', 'parent': 0, 'class_size': 8, 'enum_count': 0, 'member_count': 5, 'name_hash': 961550838 },
                    '?rflClass@DecoRimParam@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'DecoRimParam', 'parent': 0, 'class_size': 16, 'enum_count': 0, 'member_count': 4, 'name_hash': 3318808213 },
                    '?rflClass@DecoTechParam@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'DecoTechParam', 'parent': 0, 'class_size': 288, 'enum_count': 1, 'member_count': 6, 'name_hash': 3202201138 },
                    '?rflClass@GOCSimpleAnimationSpawner@rfl@heur@@2VRflClass@fnd@hh@@B': { 'name': 'GOCSimpleAnimationSpawner', 'parent': 0, 'class_size': 32, 'enum_count': 0, 'member_count': 2, 'name_hash': 398102853 },
                },
            },
        },
    },
}

def configure_rangers_analysis(game, version, platform):
    global rangers_analysis_config

    rangers_analysis_config = available_configs[game][version][platform]

known_dbs = {
    b'\x99\x89\x9acV\xdeOA\xea\xf9%\xbe`b\xf0\x13mI\xba\xc3\xf7Q|\xdc\x16\x14\x10\x84!\x86\x00\xbe': { 'game': 'rangers', 'version': '1.41', 'platform': 'steam' },
    b'\x1d\x9f\xa8\xb3\xab\x8e\x80Zx\xae\xce\x12\t\x0c\x03x\xb6iy\xe4\xe1\x84b/\x90\xd9Gaw\x11\x82\x05': { 'game': 'rangers', 'version': '1.41', 'platform': 'xbox' },
    b'\x84\xab!YF\xef{sFyZ\x13\x0c\xff\x12\x9ck|e[Y\x1a\x015u\xb3\xf4\x1a/\xec\x13\x14': { 'game': 'wars', 'version': 'latest', 'platform': 'steam' },
    b'\x8a\xb0\x10\x1a\x01D\x8ax\x01\xe7\xcb\xf7\x0chz\xd2\x7f\xb2&\x1c\xdb\x83f\rm\x97\x06>\xd7\xd1\x8d\x9c': { 'game': 'miller', 'version': '1.00', 'platform': 'steam' },
}

def autoconfigure_rangers_analysis():
    if db_desc := known_dbs[retrieve_input_file_sha256()]:
        configure_rangers_analysis(db_desc['game'], db_desc['version'], db_desc['platform'])
    else:
        raise Exception('Unknown database, cannot autoconfigure.')
